### ISSUE TITLE
Ejercicio 1 Item 1

### ISSUE THREAD

**Issue by enriqueripoli** [EMTSTISPC/Grupo6#31]
1.    Pedir el ingreso de dos números por terminal y mostrar la suma por la pantalla.

**Comment by gonaiot** [comment]
@lilenguzman01 
El ejercicio 1.1 esta bien estructurado, tien algunos comentarios aunque debe mejorar esto, de forma que cada comentario aporte a nivel de referencia particular explicando el bloque o linea, y a nivel general explicando el algoritmo. Por otro lado, si bien asignaron las tareas, no las cerraron. tenga presente esto , si no se les va a ir acumulando issues.

**Comment by lilenguzman01** [comment]
cierro issue
